### ISSUE TITLE
Achat d'un Mac (iMac ou Mac mini)

### ISSUE THREAD

**Issue by clementgalidie** [putaindecode/forum#14]
Hello !

Sujet plutôt atypique puisqu'il ne traitera pas du tout de code, mais plutôt de conseil en matière d'achat. En fait, depuis un petit mois que je bosse dans ma nouvelle société, je suis tout le temps sous Mac. Moi qui était complètement contre au début, je révise de plus en plus mon jugement et je compte m'acheter un Mac. 

Budget étudiant oblige, j'aimerais ne pas trop dépenser (si possible, je soihaiterais rester en dessous de la barre des 1000 € – pas simple dans le cas d'un iMac). 
Je vois deux possibilités : 
* Un [iMac](http://store.apple.com/fr/buy-mac/imac).
* Un [Mac mini](http://store.apple.com/fr/buy-mac/mac-mini).

J'ai contacté une vendeuse qui me propose un iMac pour 800 € dont la configuration est la suivante.
* iMac 27".
* 4 Go de RAM.
* 1 To.
* Intel Core 2 Duo 3.06 GHz.

Pour un usage comprenant uniquement du développement et de la bureautique (internet, musique, vidéo ; pas de jeux vidéo) ça me semble pas trop mal ? Par contre, et c'est là qu'est le bémol, il date d'avril 2010. 

Quels sont vos conseils ? :)

**Comment by yadomi** [comment]
@clementgalidie je confirme, pour les 8go c'est indispensable je pense, rien que pour l'évolution d'OSX qui est de plus en plus gourmand en RAM au fil des versions. 

Le Mac Mini me semble la meilleurs des solutions pour ce que tu recherches.

Par contre la souris, c'est vraiment pas indispensable... elle coute 70€ et personnellement elle ne les vaux pas car je la trouve vraiment pas pratique à utiliser et c'est loin d'être la plus ergonomique.

Et le SSD, c'est le truc qu'on se dit qu'on à pas besoins puis au final qu'on peux plus s'en passer:
- Le silence
- La sortie de veille quasi-instantanée 
- Photoshop qui s'ouvre en moins de 4 secondes
- Copier des fichiers avec une vitesse qui reste *stable*

Bref, c'est les SDD c'est magique quoi.

**Comment by bloodyowl** [comment]
j'sais pas si ça rentre dans ton budget mais à l'heure actuelle, je te conseille un MPB retina.

- portable
- retina (ce qui devient essentiel à partir du jour où tu l'as essayé)
- SSD (vitesse wow)
- performant

j'en ai un depuis 2013 et l'ordi tourne à merveille.

**Comment by clementgalidie** [comment]
Je pense partir sur le [MacBook Pro 13 pouces](http://store.apple.com/fr/buy-mac/macbook-pro) à 1449,00 €.

**Comment by yadomi** [comment]
Ça me parais être la meilleurs des solution :+1:

**Comment by MoOx** [comment]
@clementgalidie Si t'es bon, pense à fermer le ticket du coup :)

**Comment by darenju** [comment]
@bloodyowl Le Retina, c'est pas un peu pénible à gérer quand on fait du graphisme aussi ? Je veux dire, est-ce que les images sont éditées en @2x et sont complètement dégueulasse sur les non-Retina ? Et niveau batterie, en faisant une bonne journée de dev, tu tiens combien de temps ?

**Comment by bloodyowl** [comment]
nan, ça va. les images sous photoshop font un peu bizarres, mais si tu bosses en vecto sur Ai ou sketch c'est très bien. et les images images éditées en ça @2x change. et niveau batterie ça tient bien les 7/8 heures.

**Comment by darenju** [comment]
Bon finalement, j'ai aussi pris un MBPr. Effectivement, sur Sketch, rien à dire, c'est propre.
Cependant j'ai un problème, mais je pense que c'est du à l'OS : l'affichage des fenêtres en exposé (Mission Control) lag pas mal. Et de manière générale, l'interface lag. C'est assez chiant pour une machine de ce prix…

**Comment by clementgalidie** [comment]
> [...] et niveau batterie ça tient bien les 7/8 heures.
Oh putain, ça va me changer de mes pauvres 2 heures... :smile:

**Comment by clementgalidie** [comment]
Et voilà, MacBook Pro 13" avec écran retina et un petit SSD. Rien qu'avec ces deux « choses », j'hallucine !!
@darenju : je n'ai pas de souci de lag personnellement.

**Comment by kud** [comment]
Top :)

**Comment by darenju** [comment]
C'est que tu dois pas y faire gaffe, ou alors ça te gêne pas. ^^ Mais les animations de Mission Control ne sont pas toujours à 30 FPS.

**Comment by Macxim** [comment]
:wink:  https://github.com/putaindecode/forum/issues/14#issuecomment-102345773
