### ISSUE TITLE
Documentation/site d'un projet dans le repo du projet en lui même, quel arbo choisir ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/forum#16]
Je fou la doc de cssnext dans un site, dans le repo cssnext (car sinon ca casse juste les couilles à maintenir, tu oublies toujours d'update la doc etc).
Avant qu’on me demande "pourquoi ?" je souligne que j’ai pas envie de foutre le site dans un autre repo (car ca casse les couilles comme dit avant) et que de toute façon de beau projet font ça (au hasard, _react_). Du coup je me demande si je fais les tree suivant:

```
docs/
  content/ les md et html
  scripts/ les trucs pour build le site
  src/ templates & shit
```

ou 

```
docs/ les md & html
docs-src/
  scripts/
  … template & shit
```

Vous en pensez quoi ?

**Comment by madx** [comment]
Pourquoi ne pas faire une branche website orpheline ?

Sinon je verrais plutôt

```
docs/ les md & html
  website/
    scripts/ les trucs pour build le site
    src/ template & shit
```

**Comment by MoOx** [comment]
Avoir une branche orpheline revient exactement au même qu'avoir un repo à côté: quand tu fais un changement dans la lib, faut aller taper la doc ailleurs.

Hum ouais mais vu que le build prends "tout" un dossier, mettre le source du site dans le contenu du site va plus m'embeter qu'autre chose... Je pourrais ignorer mais....

**Comment by madx** [comment]
Oui je comprends pour la branche orpheline :)

Dans ton cas je pense que ta 2e solution est mieux. À la rigueur un dossier `docs/` et un dossier `website/`

**Comment by lionelB** [comment]
au risque de dire un connerie, j'aime bien l'approche de https://github.com/acdlite/flummox avec le site de la docs gérer comme un subtree

**Comment by MoOx** [comment]
Si tu parles de ça https://github.com/acdlite/flummox/tree/master/docs c'est exactement la même chose que je compte faire.

**Comment by lionelB** [comment]
oui c'est ca

**Comment by kud** [comment]
Une petite note : préférer `doc` à `docs` car c'est une abréviation. Tu n'écris pas `libs`, `srcs`, etc.

**Comment by MoOx** [comment]
Je n'ai jamais vu un repo avec "doc", mais systématiquement "docs". Pour "src" c'est car c'est "source" et non "sources". Bref ce n'est pas la discussion :)

**Comment by MoOx** [comment]
Also http://devdocs.io/ :trollface:

**Comment by kud** [comment]
```
doc/
  content/ les md et html
  scripts/ les trucs pour build le site
  src/ templates & shit
```

Je préfère tout ranger dans un et un seul dossier au sujet de la documentation.

**Comment by MoOx** [comment]
Merci pour les réponses j'ai fait ma soluce 1.
